;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Character.Action.Carry",DevComment="오브젝트 운반이 시작되거나 끝남")
GameplayTagList=(Tag="Character.Action.GetUp",DevComment="래그돌 상태가 끝나고 캐릭터가 지면에서 일어나기 시작하는 동작")
GameplayTagList=(Tag="Character.Action.Interact",DevComment="상호작용을 시작하거나 끝남")
GameplayTagList=(Tag="Character.Action.Jump",DevComment="점프 동작이 시작되거나 끝남")
GameplayTagList=(Tag="Character.Action.Sprint",DevComment="달리기 동작이 시작되거나 끝남")
GameplayTagList=(Tag="Character.Action.Throwing",DevComment="상자를 던지는 동작이 시작되거나 끝남")
GameplayTagList=(Tag="Character.Action.TriggerRagdoll",DevComment="래그돌 동작이 시작되거나 끝남")
GameplayTagList=(Tag="Character.State.Carrying",DevComment="오브젝트를 운반중인 상태")
GameplayTagList=(Tag="Character.State.Crouch",DevComment="캐릭터가 앉아있는 \'상태\'")
GameplayTagList=(Tag="Character.State.Dead",DevComment="캐릭터가 체력이 0(이하)가 되어 죽은 \'상태\'")
GameplayTagList=(Tag="Character.State.Exhausted",DevComment="캐릭터의 스태미나가 소진되어 달릴 수 없는 상태")
GameplayTagList=(Tag="Character.State.InAir",DevComment="캐릭터가 공중에 있는 상태")
GameplayTagList=(Tag="Character.State.InputReversed",DevComment="Character movement input is reversed by a status effect")
GameplayTagList=(Tag="Character.State.Ragdoll",DevComment="캐릭터가 래그돌 상태임")
GameplayTagList=(Tag="Character.State.Sprinting",DevComment="캐릭터가 달리고 있는 \'상태\'. 동작이랑 구분지으세요(UI 위젯 스위칭)")

