;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Character.State.InAir",DevComment="캐릭터가 공중에 있는 상태")
GameplayTagList=(Tag="Character.State.Ragdoll",DevComment="캐릭터가 래그돌 상태임")

