;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Item.Consumables",DevComment="기능성 아이템")
GameplayTagList=(Tag="Item.Consumables.Cart",DevComment="상자를 동시에 두 개 들 수 있게 해준다")
GameplayTagList=(Tag="Item.Cosmetics",DevComment="치장용 아이템")
GameplayTagList=(Tag="Item.Cosmetics.Skin",DevComment="캐릭터외형변화(메시,스켈레탈등)")

